create_clock -period 2.500 -name clock -waveform {0.000 1.250} -add [get_ports clk]


set_property PACKAGE_PIN G15 [get_ports {seed[0]}]
set_property PACKAGE_PIN P15 [get_ports {seed[1]}]
set_property PACKAGE_PIN W13 [get_ports {seed[2]}]
set_property PACKAGE_PIN T16 [get_ports {seed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seed[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seed[3]}]
set_property PACKAGE_PIN M14 [get_ports {led_out[0]}]
set_property PACKAGE_PIN M15 [get_ports {led_out[1]}]
set_property PACKAGE_PIN G14 [get_ports {led_out[2]}]
set_property PACKAGE_PIN D18 [get_ports {led_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]
set_property PACKAGE_PIN F20 [get_ports {yq[5]}]
set_property PACKAGE_PIN H20 [get_ports {yq[4]}]
set_property PACKAGE_PIN J19 [get_ports {yq[3]}]
set_property PACKAGE_PIN L19 [get_ports {yq[2]}]
set_property PACKAGE_PIN N20 [get_ports {yq[1]}]
set_property PACKAGE_PIN H18 [get_ports {yq[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {yq[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {yq[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {yq[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {yq[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {yq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {yq[0]}]
set_property PACKAGE_PIN L16 [get_ports clk]
set_property PACKAGE_PIN R18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

